package com.floristeriarosy.domain.exception.product;

/** Business error codes published by the product module (ADR-012). */
public enum ProductErrorCode {
  PRODUCT_NOT_FOUND,
  PRODUCT_ALREADY_EXISTS,
  PRODUCT_SLUG_RESERVED,
  PRODUCT_WITHOUT_CATEGORY,
  PRODUCT_ATTRIBUTE_UNDECLARED,
  PRODUCT_ATTRIBUTE_TYPE_MISMATCH,
  PRODUCT_NOT_AN_EXTRA,
  PRODUCT_SUGGESTS_ITSELF,
  PRODUCT_DISCONTINUED,
  PRODUCT_HAS_HISTORY,
  PRODUCT_STOCK_REQUIRED,
  PRODUCT_HAS_ACTIVE_DISCOUNT,
  PRODUCT_VALIDATION_FAILED
}
